/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyEndpointRouteImport } from './routes/api/proxy-endpoint'
import { Route as ApiWebhooksAppUninstalledRouteImport } from './routes/api/webhooks/app/uninstalled'
import { Route as ApiWebhooksAppComplianceRouteImport } from './routes/api/webhooks/app/compliance'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyEndpointRoute = ApiProxyEndpointRouteImport.update({
  id: '/api/proxy-endpoint',
  path: '/api/proxy-endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAppUninstalledRoute =
  ApiWebhooksAppUninstalledRouteImport.update({
    id: '/api/webhooks/app/uninstalled',
    path: '/api/webhooks/app/uninstalled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksAppComplianceRoute =
  ApiWebhooksAppComplianceRouteImport.update({
    id: '/api/webhooks/app/compliance',
    path: '/api/webhooks/app/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/proxy-endpoint': typeof ApiProxyEndpointRoute
  '/api/webhooks/app/compliance': typeof ApiWebhooksAppComplianceRoute
  '/api/webhooks/app/uninstalled': typeof ApiWebhooksAppUninstalledRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/proxy-endpoint': typeof ApiProxyEndpointRoute
  '/api/webhooks/app/compliance': typeof ApiWebhooksAppComplianceRoute
  '/api/webhooks/app/uninstalled': typeof ApiWebhooksAppUninstalledRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/proxy-endpoint': typeof ApiProxyEndpointRoute
  '/api/webhooks/app/compliance': typeof ApiWebhooksAppComplianceRoute
  '/api/webhooks/app/uninstalled': typeof ApiWebhooksAppUninstalledRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/proxy-endpoint'
    | '/api/webhooks/app/compliance'
    | '/api/webhooks/app/uninstalled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/proxy-endpoint'
    | '/api/webhooks/app/compliance'
    | '/api/webhooks/app/uninstalled'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/proxy-endpoint'
    | '/api/webhooks/app/compliance'
    | '/api/webhooks/app/uninstalled'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiProxyEndpointRoute: typeof ApiProxyEndpointRoute
  ApiWebhooksAppComplianceRoute: typeof ApiWebhooksAppComplianceRoute
  ApiWebhooksAppUninstalledRoute: typeof ApiWebhooksAppUninstalledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-endpoint': {
      id: '/api/proxy-endpoint'
      path: '/api/proxy-endpoint'
      fullPath: '/api/proxy-endpoint'
      preLoaderRoute: typeof ApiProxyEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/app/uninstalled': {
      id: '/api/webhooks/app/uninstalled'
      path: '/api/webhooks/app/uninstalled'
      fullPath: '/api/webhooks/app/uninstalled'
      preLoaderRoute: typeof ApiWebhooksAppUninstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/app/compliance': {
      id: '/api/webhooks/app/compliance'
      path: '/api/webhooks/app/compliance'
      fullPath: '/api/webhooks/app/compliance'
      preLoaderRoute: typeof ApiWebhooksAppComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiProxyEndpointRoute: ApiProxyEndpointRoute,
  ApiWebhooksAppComplianceRoute: ApiWebhooksAppComplianceRoute,
  ApiWebhooksAppUninstalledRoute: ApiWebhooksAppUninstalledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
